[tox]
min_version = 4
requires = tox-uv>=1
skip_missing_interpreters = true

env_list =
    3.13
    3.12
    3.7
    ruff

labels =
     test = 3.13, 3.12, 3.7
     static = ruff


[testenv]
description = run unit tests
deps =
    django >= 5
    redis >= 5.2
    hiredis >= 3.1
    msgpack-python >= 0.5
    pyyaml >= 6.0

allowlist_externals =
    ./tests/manage.py

commands =
    ./tests/manage.py test

[testenv:3.7]
deps =
    django < 2
    redis >= 5.0
    hiredis >= 2.0
    msgpack-python >= 0.5
    pyyaml >= 6.0

[testenv:ruff]
description = run ruff

deps =
    ruff

commands = ruff check
